### ISSUE TITLE
YASHE does not recognise IMPORT

### ISSUE THREAD

**Issue by andrawaag** [weso/YASHE#101]
I use YASHE a lot to verify the structure of the ShEx I write. I typically copy and paste between the Wikidata editor and YASHE. 
However, today I wrote a ShEx which contains an [IMPORT](https://biodiversity.wiki.opencura.com/wiki/EntitySchema:E2). However, when checked on YASHE, an error was given. 

<img width="1048" alt="afbeelding" src="https://user-images.githubusercontent.com/770306/73614922-053e3d80-4604-11ea-949c-63122ec3f8c5.png">

Would it be possible to support IMPORT in YASHE?

**Comment by mistermboy** [comment]
"Import" keyword was accepted by YASHE but I updated the grammar to the shex2.1 version (https://github.com/shexSpec/grammar/blob/shex2.1/bnf) which seems to be not accepted...

I will fix it as soon as possible. Thanks for your contribution :)

**Comment by mistermboy** [comment]
Resolved @andrawaag
