### ISSUE TITLE
Add support for extends and abstract keywords

### ISSUE THREAD

**Issue by labra** [weso/YASHE#167]
The new version of ShEx will include 2 new grammar rules:

```antlr
shapeExprDecl
 : KW_ABSTRACT? shapeExprLabel /* restrictions* */ (shapeExpression | KW_EXTERNAL)
 ;
```

and:

```antlr
extension
 : KW_EXTENDS shapeRef +
 | '&' shapeRef +
 ;
```

You can see the new Antlr4 grammar [here](https://github.com/weso/shex-s/blob/master/modules/shex/src/main/antlr4/ShExDoc.g4). 

It would be great to support them in Yashe.

You can see an example [here](https://cutt.ly/ghpSScJ)

**Comment by mistermboy** [comment]
It´s already implemented, thanks!
