### ISSUE TITLE
Support for multiline comments

### ISSUE THREAD

**Issue by labra** [weso/YASHE#173]
The following ShEx gives an error but it shouldn't because multi-line comments are supported by ShExC.

The ShExC grammar derivation for comments is this one: http://shex.io/shex-semantics/#term-PASSED_TOKENS

```shex
prefix : <http://example.org/>

/* 
 This is a multiline
 comment
 */
<User> {}
```

**Comment by mistermboy** [comment]
Oh, since when does ShExC support multi-line comments? Because this is the first time I've ever seen it.
I´ll try to add it soon :)

**Comment by mistermboy** [comment]
As @thewillyhuman found recently, there is a bug with the closing comment token that allows you to type */ everywhere
