### ISSUE TITLE
Placeholder option not working properly

### ISSUE THREAD

**Issue by ulitol97** [weso/YASHE#176]
When using YASHE I'd like to have a placeholder text shown when the textarea is empty, [like HTML textareas do](https://www.w3schools.com/tags/att_textarea_placeholder.asp). I've tried passing the `placeholder` option, like this:

`const options = {
  placeholder: "My placeholder text" };`
`const y = Yashe.fromTextArea(textAreaRef.current, options);`

but nothing's changing (same issue with YATE).

Maybe this [codemirror add-on](https://codemirror.net/doc/manual.html#addon_placeholder) is missing somewhere?

**Comment by mistermboy** [comment]
You´ll need to include the [Codemirror Placeholder Addon](https://codemirror.net/addon/display/placeholder.js) and then I think it will work adding the `placeholder` option to the textarea. Check the source code of this [example](https://codemirror.net/demo/placeholder.html).

Let me know if you have any problem :)

**Comment by ulitol97** [comment]
I've tried with the add-on but I'm afraid I'm not seeing any change yet, even trying and combining these different ways:
- Passing a properties object to YASHE on creation (like in my first comment)
- Changing YASHE's placeholder property after creation (`y.setOption("placeholder", "My Placeholder")`)
- Adding the placeholder attribute to the textarea element in the HTML (`<textarea... placeholder="My Placeholder"/>`)

The thing is everything's working normally in another file that uses a basic CodeMirror instance and an options object. In that case, importing some add-ons (_placeholder_, _closetag_...) did work:

- `<CodeMirror... options={{ placeholder: "My placeholder" }} />`

I'm probably missing something here... but maybe the change should come from YASHE, since it is the one eventually building the CodeMirror

**Comment by mistermboy** [comment]
I was able to make it work changing a little bit the placeholder.js. Use [this](https://gist.github.com/mistermboy/2f4dea8010a9e176407a3b335a726d20) instead the original and it should work.

Here is a working [example](https://codepen.io/mistermboy/pen/qBPrZOw)

I know it´s not the cleanest solution...I´ll try to integrate it as a YASHE option as soon as possible.

**Comment by ulitol97** [comment]
The working example looks exactly how I wanted.

I'm finally going to try this, where is the _placeholder.js_ file that must be changed?

**Comment by mistermboy** [comment]
https://gist.github.com/mistermboy/2f4dea8010a9e176407a3b335a726d20

**Comment by ulitol97** [comment]
I saw the gist, I meant the original _placeholder.js_ that must be changed with the gist's contents 😅

**Comment by mistermboy** [comment]
Oh sorry xD Unless you have imported it before, there is no original placeholder.js. I mean, in the working example I was using YASHE via CDN with the new placeholder.js as a script.  Let me know if I´m not being clear.

**Comment by ulitol97** [comment]
Thanks! I managed to make it work. It's a little hacky indeed but it will do for now. I applied the same code on YATE and and got placeholders for it as well 😇
