### ISSUE TITLE
Add information about how to compile and obtain a distribution

### ISSUE THREAD

**Issue by labra** [weso/YASHE#53]
There is no information about how to download/build the system.

Add some releases that can be downloaded, maybe from a CDN or from NPM as with YASQE

**Comment by mistermboy** [comment]
I have just updated the [readme](https://github.com/weso/YASHE/blob/gh-pages/README.md) with that information.

The simplest way is to download YASHE from JsDelivr. 
You have an example [here](https://gist.github.com/mistermboy/843d5633e5408d7d79a37b890da167f3)

**Comment by labra** [comment]
Great!, thanks!
