### ISSUE TITLE
Support for import keyword

### ISSUE THREAD

**Issue by labra** [weso/YASHE#71]
It seems that the import keyword is not accepted?

The import keyword is part of the grammar. See production rule: [4½] in http://shex.io/shex-semantics/index.html#shexc

**Comment by mistermboy** [comment]
Import keyword was accepted by YASHE but I updated the grammar to the shex2.1 version which seems to be not accepted.

https://github.com/shexSpec/grammar/blob/shex2.1/bnf

**Comment by mistermboy** [comment]
Continue in #94
